import { StyleSheet } from 'react-native';

/** Dark live theme aligned with RoundScoring / matchplay live screens. */
export const liveStablefordStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: '#07110b' },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#07110b',
    padding: 24,
  },
  loadingText: { color: '#ffffff', fontSize: 16 },
  content: { padding: 16, gap: 14 },
  headerTitle: { color: '#ffffff', fontSize: 28, fontWeight: '800' },
  headerSubtitle: { color: '#d1d5db', fontSize: 14 },
  headerMeta: { color: '#9ca3af', fontSize: 13, marginTop: 6 },
  formatRosterLine: { color: '#e5e7eb', fontSize: 14, fontWeight: '600', marginTop: 8 },
  sideRosterCard: {
    backgroundColor: '#101915',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2e3b33',
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 4,
    marginTop: 8,
  },
  sideRosterLine: { color: '#e5e7eb', fontSize: 14, fontWeight: '600' },
  leaderBanner: {
    backgroundColor: '#101915',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2e3b33',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  leaderBannerStrong: {
    backgroundColor: '#123222',
    borderColor: '#1f7a46',
  },
  leaderBannerTitle: { color: '#ffffff', fontSize: 15, fontWeight: '800', textAlign: 'center' },
  leaderBannerSub: { color: '#d1d5db', fontSize: 12, textAlign: 'center', marginTop: 4 },
  holeHero: {
    backgroundColor: '#0b1510',
    borderRadius: 18,
    paddingVertical: 22,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#1f2a23',
  },
  holeHeroLabel: {
    color: '#86efac',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  holeHeroNumber: {
    color: '#ffffff',
    fontSize: 72,
    fontWeight: '900',
    lineHeight: 84,
    marginTop: 4,
  },
  holeHeroMeta: { color: '#d1d5db', fontSize: 14, marginTop: 4 },
  navRow: { flexDirection: 'row', gap: 10 },
  navBtn: {
    flex: 1,
    backgroundColor: '#14532d',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  navBtnDisabled: { opacity: 0.35 },
  navBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 16 },
  card: {
    backgroundColor: '#0b1510',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#1f2a23',
  },
  sectionTitle: { color: '#ffffff', fontSize: 18, fontWeight: '800', marginBottom: 10 },
  sideTitle: { color: '#86efac', fontSize: 13, fontWeight: '800', marginBottom: 8 },
  holeSummaryText: { color: '#d1d5db', fontSize: 14, marginTop: 6, lineHeight: 20 },
  holeSummaryStrong: { color: '#ffffff', fontWeight: '800' },
  playerScoreRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 10,
  },
  playerMeta: { flex: 1, minWidth: 100, flexShrink: 0, paddingRight: 4 },
  playerName: { color: '#ffffff', fontSize: 17, fontWeight: '700' },
  playerSub: { color: '#9ca3af', fontSize: 12, marginTop: 2 },
  runningPts: { color: '#86efac', fontSize: 12, fontWeight: '800', marginTop: 4 },
  betterballPlayerBlock: {
    paddingVertical: 10,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1f2a23',
  },
  betterballPlayerHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 4,
  },
  betterballPlayerName: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  betterballHeaderSep: { color: '#6b7280', fontSize: 14, fontWeight: '600' },
  betterballCounting: { color: '#86efac', fontSize: 13, fontWeight: '700' },
  betterballPtsMuted: { color: '#9ca3af', fontSize: 13, fontWeight: '600' },
  betterballNrLine: { color: '#fca5a5', fontSize: 12, fontWeight: '700', marginTop: 2 },
  scoreBoxesWrap: {
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    flexShrink: 1,
    flexWrap: 'nowrap',
  },
  scoreBoxesRowBetterball: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 6,
  },
  scoreBoxGroup: { alignItems: 'center', flexShrink: 1 },
  scoreBoxGroupBetterball: { flex: 1, minWidth: 0, alignItems: 'center' },
  scoreBoxLabel: { color: '#ffffff', fontSize: 11, fontWeight: '800', marginBottom: 6 },
  scoreBoxLabelMuted: { color: '#9ca3af', fontSize: 11, fontWeight: '700', marginBottom: 6 },
  scoreInput: {
    width: 72,
    minHeight: 54,
    backgroundColor: '#101915',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#16a34a',
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
    paddingVertical: 8,
  },
  miniBox: {
    minWidth: 48,
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2e3b33',
    backgroundColor: '#101915',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  miniBoxText: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  pointsBox: {
    minWidth: 56,
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  pointsBoxEmpty: { backgroundColor: '#0f1713', borderColor: '#2e3b33' },
  pointsBoxLow: { backgroundColor: '#17201b', borderColor: '#3f4d45' },
  pointsBoxActive: { backgroundColor: '#123222', borderColor: '#1f7a46' },
  pointsBoxGood: { backgroundColor: '#14532d', borderColor: '#16a34a' },
  pointsBoxText: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  holeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  holeChip: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#101915',
    borderWidth: 1,
    borderColor: '#334155',
  },
  holeChipSelected: { backgroundColor: '#16a34a', borderColor: '#16a34a' },
  holeChipComplete: { borderColor: '#86efac' },
  holeChipText: { color: '#ffffff', fontWeight: '800' },
  holeChipTextSelected: { color: '#ffffff' },
  actionRow: { flexDirection: 'row', gap: 10, marginBottom: 24 },
  tertiaryBtn: {
    flex: 1,
    backgroundColor: '#101915',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2e3b33',
    paddingVertical: 15,
    alignItems: 'center',
  },
  tertiaryBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 16 },
  secondaryBtn: {
    flex: 1,
    backgroundColor: '#1f2a23',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  secondaryBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 16 },
  primaryBtn: {
    flex: 1,
    backgroundColor: '#16a34a',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
  },
  primaryBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 16 },
  warnCard: {
    backgroundColor: '#1a221d',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#4b5563',
  },
  warnTitle: { color: '#ffffff', fontSize: 16, fontWeight: '800', marginBottom: 8 },
  warnBody: { color: '#d1d5db', fontSize: 14, lineHeight: 20 },
});
