import { Share } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

export type HandicapExportPlayer = {
  name: string;
  handicapIndex: number | null;
  courseHandicap: number | null;
  playingHandicap: number | null;
};

export type HandicapExportTeam = {
  title: string;
  players: HandicapExportPlayer[];
  enteredCount: number;
  averageHandicapIndex: number | null;
  averagePlayingHandicap: number | null;
};

export type HandicapExportPayload = {
  title: string;
  generatedAt: string;
  courseName: string;
  teeName: string | null;
  courseRating: number | null;
  slopeRating: number | null;
  par: number | null;
  allowancePercent: number;
  roundingMode: 'round' | 'floor' | 'ceil';
  teamA: HandicapExportTeam;
  teamB: HandicapExportTeam;
};

const PLACEHOLDER_PLAYER_NAME = /^player\s*\d*$/i;

export function isRealHandicapPlayerName(name: string): boolean {
  const trimmed = name.trim();
  if (!trimmed) return false;
  return !PLACEHOLDER_PLAYER_NAME.test(trimmed);
}

export function isExportableHandicapPlayer(player: HandicapExportPlayer): boolean {
  if (isRealHandicapPlayerName(player.name)) return true;
  const hi = player.handicapIndex;
  if (hi == null || hi === 0) return false;
  return false;
}

export function filterExportableHandicapPlayers(
  players: HandicapExportPlayer[]
): HandicapExportPlayer[] {
  return players.filter(isExportableHandicapPlayer);
}

function average(values: number[]): number | null {
  if (!values.length) return null;
  const total = values.reduce((sum, v) => sum + v, 0);
  return Number((total / values.length).toFixed(1));
}

export function summarizeHandicapExportPlayers(players: HandicapExportPlayer[]): {
  enteredCount: number;
  averageHandicapIndex: number | null;
  averagePlayingHandicap: number | null;
} {
  const entered = filterExportableHandicapPlayers(players);
  return {
    enteredCount: entered.length,
    averageHandicapIndex: average(
      entered.map((p) => p.handicapIndex).filter((v): v is number => v != null)
    ),
    averagePlayingHandicap: average(
      entered.map((p) => p.playingHandicap).filter((v): v is number => v != null)
    ),
  };
}

function formatMaybe(value: number | null): string {
  return value == null ? '-' : String(value);
}

function formatRoundingModeLabel(mode: HandicapExportPayload['roundingMode']): string {
  if (mode === 'floor') return 'Floor';
  if (mode === 'ceil') return 'Ceil';
  return 'Round';
}

function safeFilenamePart(value: string): string {
  return value
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function safe(value: string): string {
  return value.replace(/[&<>"']/g, (c) => {
    if (c === '&') return '&amp;';
    if (c === '<') return '&lt;';
    if (c === '>') return '&gt;';
    if (c === '"') return '&quot;';
    return '&#39;';
  });
}

function lineForPlayer(player: HandicapExportPlayer): string {
  return `${player.name.trim()} — HI ${formatMaybe(player.handicapIndex)} · CH ${formatMaybe(player.courseHandicap)} · PH ${formatMaybe(player.playingHandicap)}`;
}

function compactCourseLines(payload: HandicapExportPayload): string[] {
  const tee = payload.teeName?.trim() ? payload.teeName.trim() : '-';
  return [
    `Course: ${payload.courseName}    Tee: ${tee}`,
    `Rating: ${formatMaybe(payload.courseRating)}    Slope: ${formatMaybe(payload.slopeRating)}    Par: ${formatMaybe(payload.par)}`,
    `Allowance: ${payload.allowancePercent}%    Rounding: ${formatRoundingModeLabel(payload.roundingMode)}`,
  ];
}

function teamText(team: HandicapExportTeam): string {
  const players = filterExportableHandicapPlayers(team.players);
  const summary = summarizeHandicapExportPlayers(team.players);
  const lines = players.map((p) => `- ${lineForPlayer(p)}`);
  return [
    team.title,
    `Players entered: ${summary.enteredCount} · Avg HI: ${formatMaybe(summary.averageHandicapIndex)} · Avg PH: ${formatMaybe(summary.averagePlayingHandicap)}`,
    ...(lines.length ? lines : ['- No players entered']),
  ].join('\n');
}

export function buildCompetitionSummaryText(payload: HandicapExportPayload): string {
  return [
    payload.title,
    `Generated: ${new Date(payload.generatedAt).toLocaleString()}`,
    '',
    ...compactCourseLines(payload),
    '',
    teamText(payload.teamA),
    '',
    teamText(payload.teamB),
    '',
    'Generated by NetParGolf',
  ].join('\n');
}

function teamRowsHtml(team: HandicapExportTeam): string {
  const players = filterExportableHandicapPlayers(team.players);
  const summary = summarizeHandicapExportPlayers(team.players);
  const rows = players
    .map((p) => {
      const name = p.name.trim();
      return `<tr><td>${safe(name)}</td><td>${safe(formatMaybe(p.handicapIndex))}</td><td>${safe(formatMaybe(p.courseHandicap))}</td><td>${safe(formatMaybe(p.playingHandicap))}</td></tr>`;
    })
    .join('');

  const body =
    rows || '<tr><td colspan="4" style="text-align:center;color:#666">No players entered</td></tr>';

  return `
    <section class="team-section">
      <h2>${safe(team.title)}</h2>
      <p class="summary">Players entered: ${summary.enteredCount} · Avg HI: ${safe(
        formatMaybe(summary.averageHandicapIndex)
      )} · Avg PH: ${safe(formatMaybe(summary.averagePlayingHandicap))}</p>
      <table>
        <thead><tr><th>Name</th><th>HI</th><th>CH</th><th>PH</th></tr></thead>
        <tbody>${body}</tbody>
      </table>
    </section>
  `;
}

function courseCardHtml(payload: HandicapExportPayload): string {
  const tee = payload.teeName?.trim() ? payload.teeName.trim() : '-';
  return `
    <div class="course-card">
      <div class="course-line">
        <span><strong>Course:</strong> ${safe(payload.courseName)}</span>
        <span><strong>Tee:</strong> ${safe(tee)}</span>
      </div>
      <div class="course-line">
        <span><strong>Rating:</strong> ${safe(formatMaybe(payload.courseRating))}</span>
        <span><strong>Slope:</strong> ${safe(formatMaybe(payload.slopeRating))}</span>
        <span><strong>Par:</strong> ${safe(formatMaybe(payload.par))}</span>
      </div>
      <div class="course-line">
        <span><strong>Allowance:</strong> ${payload.allowancePercent}%</span>
        <span><strong>Rounding:</strong> ${safe(formatRoundingModeLabel(payload.roundingMode))}</span>
      </div>
    </div>
  `;
}

export function buildCompetitionSummaryHtml(payload: HandicapExportPayload): string {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${safe(payload.title)}</title>
<style>
  @page {
    size: A4;
    margin: 12mm;
  }
  body {
    font-family: Arial, sans-serif;
    color: #111;
    padding: 0;
    margin: 0;
    font-size: 12px;
  }
  h1 {
    margin: 0 0 4px 0;
    font-size: 20px;
    line-height: 1.2;
  }
  h2 {
    margin: 0 0 6px 0;
    font-size: 16px;
    line-height: 1.2;
  }
  .meta {
    color: #555;
    font-size: 11px;
    margin-bottom: 8px;
  }
  .course-card {
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 8px 10px;
    margin-bottom: 10px;
    background: #fafafa;
  }
  .course-line {
    display: flex;
    flex-wrap: wrap;
    gap: 8px 16px;
    margin-bottom: 4px;
    line-height: 1.35;
  }
  .course-line:last-child {
    margin-bottom: 0;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 6px;
    page-break-inside: auto;
  }
  th, td {
    border: 1px solid #ccc;
    padding: 5px 7px;
    font-size: 11px;
    text-align: left;
  }
  th {
    background: #f3f4f6;
    font-weight: 800;
  }
  tr {
    page-break-inside: avoid;
    break-inside: avoid;
  }
  .summary {
    font-size: 11px;
    color: #333;
    margin: 0 0 4px 0;
  }
  .team-section {
    page-break-inside: avoid;
    break-inside: avoid;
    margin-top: 14px;
  }
</style>
</head>
<body>
  <h1>${safe(payload.title)}</h1>
  <div class="meta">Generated: ${safe(new Date(payload.generatedAt).toLocaleString())} · NetParGolf</div>
  ${courseCardHtml(payload)}
  ${teamRowsHtml(payload.teamA)}
  ${teamRowsHtml(payload.teamB)}
</body>
</html>`;
}

export async function shareCompetitionSummary(payload: HandicapExportPayload): Promise<void> {
  const message = buildCompetitionSummaryText(payload);
  await Share.share({ message, title: payload.title });
}

function buildHandicapPdfFilename(payload: HandicapExportPayload): string {
  const safeCourse = safeFilenamePart(payload.courseName) || 'Course';
  const ymd = new Date(payload.generatedAt).toISOString().slice(0, 10).replace(/-/g, '');
  const teamALabel = payload.teamA.title.trim();
  const teamBLabel = payload.teamB.title.trim();
  const teamA = safeFilenamePart(teamALabel);
  const teamB = safeFilenamePart(teamBLabel);
  const hasCustomA = teamALabel.length > 0 && teamALabel !== 'Team A';
  const hasCustomB = teamBLabel.length > 0 && teamBLabel !== 'Team B';
  if (hasCustomA && hasCustomB) {
    return `NetParGolf_HandicapSheet_${safeCourse}_${teamA}_vs_${teamB}_${ymd}.pdf`;
  }
  if (hasCustomA) {
    return `NetParGolf_HandicapSheet_${safeCourse}_${teamA}_${ymd}.pdf`;
  }
  if (hasCustomB) {
    return `NetParGolf_HandicapSheet_${safeCourse}_${teamB}_${ymd}.pdf`;
  }
  return `NetParGolf_HandicapSheet_${safeCourse}_${ymd}.pdf`;
}

export async function exportCompetitionPdf(payload: HandicapExportPayload): Promise<string> {
  const html = buildCompetitionSummaryHtml(payload);
  const { uri } = await Print.printToFileAsync({ html });
  const dir = FileSystem.cacheDirectory ?? FileSystem.documentDirectory;
  const filename = buildHandicapPdfFilename(payload);
  const namedUri = dir ? `${dir}${filename}` : uri;
  if (dir) {
    await FileSystem.copyAsync({ from: uri, to: namedUri });
  }
  const shareOk = await Sharing.isAvailableAsync();
  if (!shareOk) return namedUri;
  await Sharing.shareAsync(namedUri, { mimeType: 'application/pdf' });
  return namedUri;
}

export async function saveCompetitionSummaryTextFile(payload: HandicapExportPayload): Promise<string> {
  const dir = FileSystem.cacheDirectory ?? FileSystem.documentDirectory;
  if (!dir) throw new Error('Storage not available');
  const filename = `netpargolf-handicap-summary-${Date.now()}.txt`;
  const uri = `${dir}${filename}`;
  await FileSystem.writeAsStringAsync(uri, buildCompetitionSummaryText(payload), {
    encoding: FileSystem.EncodingType.UTF8,
  });
  return uri;
}
